apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: promtail
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 3101
      grpc_listen_port: 0

    clients:
      - url: "https://logs-prod-us-central1.grafana.net/loki/api/v1/push"
        basic_auth:
          username: "<grafana cloud user>"
          password: "<grafana cloud password>"

    scrape_configs:
      - job_name: kubernetes-audit-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: "kubernetes-audit-logs"
              __path__: /var/log/kubernetes/kube-apiserver.log
