---
apiVersion: v1
kind: Namespace
metadata:
  name: test-volume-attach
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
  name: test-volume-attach
  namespace: test-volume-attach
rules:
- apiGroups:
  - extensions
  resourceNames:
   - pks-privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-volume-attach
  namespace: test-volume-attach
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-volume-attach
  namespace: test-volume-attach
subjects:
- kind: ServiceAccount
  name: test-volume-attach
  namespace: test-volume-attach
roleRef:
  kind: Role
  name: test-volume-attach
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-volume-attach
  namespace: test-volume-attach
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: demo-csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: test-volume-attach
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test-container
          image: busybox:1.24
          command: ["/bin/sh", "-c", "while true ; do sleep 2 ; done"]
          volumeMounts:
            - name: test-volume
              mountPath: /test
      volumes:
        - name: test-volume
          persistentVolumeClaim:
            claimName: test-volume-attach
      serviceAccountName: test-volume-attach
