---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: demo-csi
  annotations:
      storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
allowVolumeExpansion: true
