apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-goose-cnb
  labels:
    app: hello-goose-cnb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-goose-cnb
  template:
    metadata:
      labels:
        app: hello-goose-cnb
    spec:
      imagePullSecrets: 
      - name: harbor-registry-secret
      containers:
      - name: hello-goose-cnb
        image: 10.213.190.66/tkgs-test-andy/hello-goose
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
          - name: CF_INSTANCE_INDEX
            value: kubernetes
          - name: CF_INSTANCE_GUID
            value: kubernetes
