apiVersion: v1
kind: Service
metadata:
  name: hello-goose-cnb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-goose-cnb
  loadBalancerIP: 10.213.190.68
  type: LoadBalancer
