apiVersion: v1
kind: Service
metadata:
  name: hello-goose-cnb-2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-goose-cnb
  loadBalancerIP: 8.8.8.8
  type: LoadBalancer
