apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: knappster-de-example
  namespace: default
spec:
  secretName: example-knappster-de-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  dnsNames:
  - example.knappster.de
